version: "3.8"
services:
  app:
    image: digitalfrontend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 2000M
