version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      - MYSQL_ROOT_PASSWORD=4230
      - MYSQL_DATABASE=career_test
    ports:
      - 3307:3306
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    build: ./backend
    restart: on-failure
    env_file: ./backend/.env
    ports:
      - 8089:8080
    environment:
      SECRET: zdtlD3JK56m6wTTgsNFhqzjqP
      DB_URL: jdbc:mysql://mysqldb:3306/career_test?useSSL=false
      PSWORD: 4230
      USRNM: root
    volumes:
      - .db:/root/.db
      - ./logs:/app/logs
    stdin_open: true
    tty: true

  front:
    image: digitalfrontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_SERVER_URL: http://localhost:8089
    deploy:
      resources:
        limits:
          memory: 3000M

volumes:
  db:
